#!/usr/bin/env ruby
# encoding: UTF-8

# This script will automate update plugin list in Readme.md

root = `git rev-parse --show-toplevel`.chomp
helper_path = File.join(root, 'helper')

load File.join(helper_path, 'plugin_list.rb')
file_list = `git add -A --dry-run`.split("\n")
unless file_list.grep(/'Readme\.md'/).empty?
  system 'git add Readme.md'
  system %q(git commit -m 'Update readme')
end

